# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'invoice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinvoice.proto\x12\x07invoice\"e\n\x0eInvoiceRequest\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x01\x12\x12\n\nissue_date\x18\x04 \x01(\t\"3\n\x0fInvoiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x14InvoiceLookupRequest\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\"\x8b\x01\n\x12GetInvoiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ninvoice_id\x18\x03 \x01(\t\x12\x15\n\rcustomer_name\x18\x04 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x05 \x01(\x01\x12\x12\n\nissue_date\x18\x06 \x01(\t\"\r\n\x0b\x45mptyLookup\"b\n\x0bInvoiceData\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x01\x12\x12\n\nissue_date\x18\x04 \x01(\t\"`\n\x14ListInvoicesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x08invoices\x18\x03 \x03(\x0b\x32\x14.invoice.InvoiceData2\xac\x02\n\x0eInvoiceService\x12\x41\n\x0cSaveMetadata\x12\x17.invoice.InvoiceRequest\x1a\x18.invoice.InvoiceResponse\x12H\n\nGetInvoice\x12\x1d.invoice.InvoiceLookupRequest\x1a\x1b.invoice.GetInvoiceResponse\x12\x43\n\x0cListInvoices\x12\x14.invoice.EmptyLookup\x1a\x1d.invoice.ListInvoicesResponse\x12H\n\rDeleteInvoice\x12\x1d.invoice.InvoiceLookupRequest\x1a\x18.invoice.InvoiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOICEREQUEST']._serialized_start=26
  _globals['_INVOICEREQUEST']._serialized_end=127
  _globals['_INVOICERESPONSE']._serialized_start=129
  _globals['_INVOICERESPONSE']._serialized_end=180
  _globals['_INVOICELOOKUPREQUEST']._serialized_start=182
  _globals['_INVOICELOOKUPREQUEST']._serialized_end=224
  _globals['_GETINVOICERESPONSE']._serialized_start=227
  _globals['_GETINVOICERESPONSE']._serialized_end=366
  _globals['_EMPTYLOOKUP']._serialized_start=368
  _globals['_EMPTYLOOKUP']._serialized_end=381
  _globals['_INVOICEDATA']._serialized_start=383
  _globals['_INVOICEDATA']._serialized_end=481
  _globals['_LISTINVOICESRESPONSE']._serialized_start=483
  _globals['_LISTINVOICESRESPONSE']._serialized_end=579
  _globals['_INVOICESERVICE']._serialized_start=582
  _globals['_INVOICESERVICE']._serialized_end=882
# @@protoc_insertion_point(module_scope)
